import os
import shutil
import sys

def update_ad_image(source_path, destination_name="ad_image.jpg", html_dir="."):
    """
    Copies the latest generated image to a standard name expected by fixer.html.
    
    Args:
        source_path (str): The full path to the image generated by nano banana (or any source).
        destination_name (str): The standard filename expected by fixer.html (e.g., ad_image.jpg).
        html_dir (str): The directory where fixer.html is located.
    """
    
    destination_path = os.path.join(html_dir, destination_name)
    
    try:
        shutil.copyfile(source_path, destination_path)
        print(f"✅ Successfully copied '{os.path.basename(source_path)}' to '{destination_path}'")
        print(f"You can now open 'fixer.html' to edit the text.")
    except FileNotFoundError:
        print(f"❌ Error: Source file not found at '{source_path}'")
    except Exception as e:
        print(f"❌ An error occurred during copy: {e}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python setup_fixer.py <path_to_source_image>")
        print("Example: python setup_fixer.py C:/Images/my_render.png")
    else:
        source_image = sys.argv[1]
        update_ad_image(source_image)
